### ISSUE TITLE
Refactor API connector into separate client

### ISSUE THREAD

**Issue by cdharini** [VolunteerForce/main#10]

**Comment by jenda** [comment]
btw, when working on https://github.com/VolunteerForce/main/issues/9 I sort had to do it already... it's still not perfect but at least something... check `BetterPlaceDataProvider`

**Comment by jenda** [comment]
I assume that this involves search and filter events too as described in here:
https://docs.google.com/document/d/1F_mepCT9BaTCb3PPIhYkbBqLBUz3xmzM814sY_sGzK4/edit#

?

**Comment by cdharini** [comment]
Yes I will be adding methods to the dataprovider to get events based on filter as well

**Comment by cdharini** [comment]
Added more params to the BetterPlaceClient to support filtering by location and search query string.
