### ISSUE TITLE
Save subscribe event to Firebase

### ISSUE THREAD

**Issue by cdharini** [VolunteerForce/main#12]

**Comment by tejal-par** [comment]
@cdharini 
We called it here today: https://github.com/VolunteerForce/main/blob/master/VolunteerHero/app/src/main/java/com/codepath/volunteerhero/fragments/EventDetailFragment.java#L88

Later I have updated the implementation to take care of appending events to existing list of subcriptions
107c4b5d7c8cb7ddfbc9e710868eb2a6f9673ff9
