### ISSUE TITLE
 Getting user profile pic

### ISSUE THREAD

**Issue by jenda** [VolunteerForce/main#15]
- get the URL for user profile pic

**Comment by tejal-par** [comment]
We have url for user profile, added logic to fetch image.
d5d78bfd5ac9a5a41f777772e40a2456a5d76070
c8c18214613a0da5e65b75e25919247171dc4e6e

**Comment by tejal-par** [comment]
Added a fix
1808b27075379d8c4fc45cf9270c1ab1c75c350e

**Comment by tejal-par** [comment]
Added first login:
8964e8728da5dd986283c3e917c27503e748a224
