### ISSUE TITLE
 Beautify List of events view

### ISSUE THREAD

**Issue by jenda** [VolunteerForce/main#24]

**Comment by cdharini** [comment]
@tejaldev Can we replace the 3 lines for the navigation view with the logo? The titlebar looks too full with logo and the nav view icon and the name of the app and the Filter icon. Let me know if you agree.

**Comment by tejal-par** [comment]
@cdharini yes I do feel its bit cluttered. We can have just the logo I guess might look better. Il do the change.

**Comment by tejal-par** [comment]
ok replaced nav view icon with logo here: 9b091b99d5b68813e3348e04ff7ba86d61107a41
