### ISSUE TITLE
 Login/logout polish

### ISSUE THREAD

**Issue by jenda** [VolunteerForce/main#30]
make login activity and logout button look pretty

**Comment by cdharini** [comment]
@tejaldev  The full png for the logo is located In the src/main folder if you want to use it for the login screen..

**Comment by tejal-par** [comment]
Ah thanks @cdharini

**Comment by tejal-par** [comment]
341c03a0f5cf9a796dacc87263eadb5c55911d49
4ca499b7eb1ffa25efb97fa0ca502ca4e1a37c71
2a094ef8cbfad48544f0294c154e07c89c5fc333
