### ISSUE TITLE
when click on subscribe the app looks like it restarted

### ISSUE THREAD

**Issue by jenda** [VolunteerForce/main#33]
that's really bad behavior. we should just finish the activity (look how I did that in delete event button)

**Comment by cdharini** [comment]
@jenda I am calling finishActivity the same way it is being done for the delete button, not sure why the screen transition animation looks different. The one thing is that once an event is subscribed to, it is added to Firebase which triggers a dataLoad on the main activity, maybe this is causing it to look like the activity loads again?

**Comment by jenda** [comment]
not worth fixing it.
