### ISSUE TITLE
Better UI for create event

### ISSUE THREAD

**Issue by cdharini** [VolunteerForce/main#7]
1. Images
2. Topics
3. Add current user as "Carrier"

**Comment by jenda** [comment]
Images:

1. finalizing issues with camera:
https://github.com/VolunteerForce/main/commit/f1c2802b1677b8dc736b129035b914c9b5811b80

2. image upload to imgur:
https://github.com/VolunteerForce/main/commit/6dc3404b0dd032a27137eb332b869f535ad848eb
https://github.com/VolunteerForce/main/commit/6f6e927afed5227dc09bb782e9f66829742a128a
